linux-setup-steps: &linux-setup-steps
  dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
  os: linux
  language: python
  install:
    - pip install --upgrade pip pipenv
    - pipenv install --dev
    - sudo apt-get install ninja-build

windows-setup-steps: &windows-setup-steps
  os: windows
  language: shell  # 'language: python' is not yet supported on Windows
  env:
    - GYP_MSVS_VERSION=2017
    - PYTHONUNBUFFERED=1
  install:
    - python -m pip install --upgrade pip pipenv
    - python -m pipenv install --dev

osx-setup-steps: &osx-setup-steps
  os: osx
  language: cpp  # 'language: python' is not yet supported on macOS
  # before_install: brew upgrade python  # takes too long
  install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
    - pip install --upgrade pip pipenv
    - pipenv install --dev
    - pipenv install PyObjC  # This is not in the Pipfile because it breaks other platforms https://github.com/pypa/pipenv/issues/3187

matrix:
  include:
    - name: "Linux: test with make and ninja on Python 3.7"
      python: '3.7'
      <<: *linux-setup-steps
      script: pipenv run -v test -f make,ninja

    - name: "macOS: test with make and ninja on Python 3.7"
      <<: *osx-setup-steps
      script: pipenv run -v test -f make,ninja

    - name: "macOS: XCode10.2 test with make and ninja on Python 3.7"
      os: osx
      osx_image: xcode10.2  # provides Python 3.7.2
      language: cpp  # 'language: python' is not yet supported on macOS
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
        - pip3 install --upgrade pip pipenv
        - pipenv install --dev
        - pipenv install PyObjC  # This is not in the Pipfile because it breaks other platforms https://github.com/pypa/pipenv/issues/3187
      script: pipenv run -v test -f make,ninja

notifications:
  slack: node4good:C2EI9vo04FY8Ce5u7kcOLlDw
